var globalVar = "Soy una variable global";


let localVar = "Soy una variable local";


const mes = "Mayo";


let numeroEntero = 42;
let numeroDecimal = 3.14;
let cadenaTexto = "Hola, mundo";
let booleano = true;
let arreglo = [1, 2, 3, 4, 5];
let objeto = { nombre: "Juan", edad: 30 };
let indefinida;
let nulo = null;


function operacion(a, b) {
    return a + b;
}


console.log("Variable global:", globalVar);
console.log("Variable local:", localVar);
console.log("Constante mes:", mes);
console.log("Número entero:", numeroEntero);
console.log("Número decimal:", numeroDecimal);
console.log("Cadena de texto:", cadenaTexto);
console.log("Booleano:", booleano);
console.log("Arreglo:", arreglo);
console.log("Objeto:", objeto);
console.log("Indefinida:", indefinida);
console.log("Nulo:", nulo);
console.log("Operación (5 + 3):", operacion(5, 3));
